export const articles = {
  name: 'articles',
  methods: {
    create: 'ArticlesActions.create',
    findAll: 'ArticlesActions.findAll',
    update: 'ArticlesActions.update',
    deleteMany: 'ArticlesActions.delete',
  },
  types: {
    REQUEST_ENTITY: 'REQUEST_ARTICLE',
    RECEIVE_ENTITY: 'RECEIVE_ARTICLE',
    SORT_ENTITY: 'SORT_ARTICLE',
    UPDATE_ENTITY: 'UPDATE_ARTICLE',
    DELETE_ENTITY: 'DELETE_ARTICLE',
    CHANGE_FILTER: 'CHANGE_FILTER_ARTICLES',
    CHANGE_FILTER_VALUE: 'CHANGE_FILTER_VALUE_ARTICLES',
  },
  options: [
    {
      name: 'checkbox',
      searchable: false,
      sortable: false,
      editable: true,
      specifyOnCreate: false,
      label: '',
      inputType: 'checkbox',
    },
    {
      name: 'number',
      searchable: false,
      sortable: false,
      editable: false,
      specifyOnCreate: false,
      label: 'Number',
      inputType: 'text',
    },
    {
      name: 'title',
      searchable: true,
      sortable: true,
      editable: true,
      specifyOnCreate: true,
      required: true,
      label: 'Title',
      inputType: 'text',
    },
    {
      name: 'text',
      searchable: false,
      sortable: false,
      editable: true,
      specifyOnCreate: true,
      required: false,
      label: 'Article text',
      inputType: 'text',
    },
    {
      name: 'authorId',
      searchable: true,
      sortable: true,
      editable: true,
      specifyOnCreate: true,
      required: true,
      label: 'Author',
      inputType: 'text',
    },
    {
      name: 'publicationDate',
      searchable: true,
      sortable: true,
      editable: true,
      specifyOnCreate: false,
      label: 'Publication date',
      inputType: 'date',
    },
  ],
  initialState: () => ({
    filter: 'title',
    filterValue: '',
    sorting: [ 'title', 'ASC' ],
    headerProps: articles.options,
  }),
};

export const websites = {
  name: 'websites',
  methods: {
    create: 'WebsitesActions.create',
    findAll: 'WebsitesActions.findAll',
    update: 'WebsitesActions.update',
    deleteMany: 'WebsitesActions.delete',
  },
  types: {
    REQUEST_ENTITY: 'REQUEST_WEBSITE',
    RECEIVE_ENTITY: 'RECEIVE_WEBSITE',
    SORT_ENTITY: 'SORT_WEBSITE',
    UPDATE_ENTITY: 'UPDATE_WEBSITE',
    DELETE_ENTITY: 'DELETE_WEBSITE',
    CHANGE_FILTER: 'CHANGE_FILTER_WEBSITE',
    CHANGE_FILTER_VALUE: 'CHANGE_FILTER_VALUE_WEBSITE',
  },
  options: [
    {
      name: 'checkbox',
      searchable: false,
      sortable: false,
      editable: true,
      specifyOnCreate: false,
      label: '',
      inputType: 'checkbox',
    },
    {
      name: 'number',
      searchable: false,
      sortable: false,
      editable: false,
      specifyOnCreate: false,
      label: 'Number',
      inputType: 'text',
    },
    {
      name: 'title',
      searchable: true,
      sortable: true,
      editable: true,
      specifyOnCreate: true,
      required: true,
      label: 'Title',
      inputType: 'text',
    },
    {
      name: 'description',
      searchable: false,
      sortable: false,
      editable: true,
      specifyOnCreate: true,
      required: false,
      label: 'Description',
      inputType: 'text',
    },
    {
      name: 'url',
      searchable: false,
      sortable: false,
      editable: true,
      specifyOnCreate: true,
      required: true,
      label: 'URL',
      inputType: 'text',
    },
    {
      name: 'visitorsCount',
      searchable: false,
      sortable: true,
      editable: true,
      specifyOnCreate: false,
      label: 'Visitors count',
      inputType: 'text',
    },
  ],
  initialState: () => ({
    filter: 'title',
    filterValue: '',
    sorting: [ 'title', 'ASC' ],
    headerProps: websites.options,
  }),
};

export const ARTICLE_TYPES = articles.types;
export const WEBSITE_TYPES = websites.types;

export default {
  articles,
  websites,
};
